name: quantum_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  sqflite: ^2.2.8
  path: ^1.8.3
  flutter_local_notifications: 
  google_fonts: ^5.1.0
  equatable: ^2.0.5
  timezone: 
  uuid: ^3.0.7
  intl: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
